mydjango19/diary/urls.py
from django.urls import path

from diary import views
from . import views

app_name = 'diary'  # 이제 이 이름으료 url reverse에서 사용

urlpatterns = [
    path("", views.post_list, name="post_list"),  # 함수만 지정.
    path("<int:pk>/", views.post_detail, name="post_detail"),
    path("new/", views.post_new, name="post_new"),
    path("<int:pk>/edit/", views.post_edit, name="post_edit"),
    path("tags/<str:tag_name>/",views.tag_detail, name='tag_detail'),
    path("<int:post_pk>/comments/new/", views.comment_new, name="comment_new"),
    path("<int:post_pk>/comments/<int:pk>/edit/", views.comment_edit, name="comment_edit"),

]

mynote1/mynote1/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

from django.contrib import admin
from django.urls import path

from dog.views import post_list, post_detail

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dog/', post_list),
    path('dog/<int:pk>', post_detail),

]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

mynote2/diary/urls.py
from django.urls import path

from . import views
app_name = 'diary'  # 보통 앱 이름을 한번 써줌

# name = 이 함수의 이름은~ 이라는 뜻
urlpatterns = [
    path("", views.post_list, name="post_list"),  # 함수만 지정.

]

mynote3/diary/urls.py
from django.urls import path

from diary import views
from . import views

app_name = 'diary'  # 보통 앱 이름을 한번 써줌

# name = 이 함수의 이름은~ 이라는 뜻
urlpatterns = [
    path("", views.post_list, name="post_list"),  # 함수만 지정.
    path("<int:pk>/", views.post_detail, name="post_detail"),
    path("tags/<str:tag_name>/",views.tag_detail, name='tag_detail'),
]

# urlpatterns = [
# path("", list, name= ]

# 부모 layout.html은 상속을 해주기 위해서만 존재하는 것.
# 자식이 할 수 있는 일은? 부모가 정의한 block에 content를 공급하는 것 밖에 없음

test02/test02/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

mydjango17/diary/models.py
from django.db import models


# 상속받아서 정의 하기
# 필드가 정의된 부모로서만 동작하기를 기대함 .


class TimestampedModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True  # 추상 클래스로서, DB 테이블이 생기지 않는다.
        # 단순히 부모로서만 동작한다.


class Post(TimestampedModel):  # 모델 상속을 받아서, 모델의 개념을 가져오는 것
    author_name = models.CharField(max_length=20)
    title = models.CharField(max_length=200, db_index=True)
    #  db_index=True 를 하고, makemigrations를 해야 인덱스가 생성이된다!
    content = models.TextField()

    # media 폴더 밑에 저장이 된다
    photo = models.ImageField(upload_to='diary/post/%Y/%M/%d')

    tag_set = models.ManyToManyField('Tag', blank=True)

    # Tag 클래스는 밑에있다. 그래서 ? 얘를 'tag'이렇게 문자열로 감싸주면
    # 장고에서 알아서 Tag를 찾아서 적용해준다 !

    def __str__(self) -> str:
        return self.title

    class Meta:
        verbose_name = "포스팅"  # 단수
        verbose_name_plural = "포스팅 목록"  # 복수


# 1 : N 관계에서, 하나의 포스트가 삭제되었을때, 거기에 있을 댓글들은 어떻게 할래?
# on_delete=models.CASCADE -> 포스트가 삭제되었을때, 댓글들도 같이 지워줌
# Foreignkey추가
class Comment(TimestampedModel):
    # 외래키는 정수값을 지정해야 함

    # 밑에 처럼 지정해주면? post_id라는 필드를 자동으로 생성해줌
    # 외래키에 한해서는, 이름_id라는 필드가 생기게 됨.
    # 실제 DB의 외래키는 post_id인 거고 ~

    post = models.ForeignKey('Post', on_delete=models.CASCADE)  # class가 위에있으니까 문자열로 지정 해도 돼
    author_name = models.CharField(max_length=20)
    message = models.TextField()

    class Meta:
        verbose_name = "댓글"  # 단수
        verbose_name_plural = "댓글 목록"  # 복수


class Tag(TimestampedModel):
    # 보통 태그에는 태그 명 정도 !
    name = models.CharField(max_length=200, db_index=True)

    def __str__(self) -> str:
        return f"[{self.pk}] {self.name}"

    class Meta:
        verbose_name = "태그"  # 단수
        verbose_name_plural = "태그 목록"  # 복수

mydjango19/diary/forms.py
from django import forms
from diary.models import Post,Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        # 유저로부터 입력받을 필드 이름을 나열(ip빼고)
        fields = [
            "author_name",
            "title",
            "content",
            "photo",
            "tag_set",
        ]
        # 나는 여기에 명시한 필드들의 값들만 받겠다!!!!


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        # fields는 리스트가 아님
       # fields = "__all__" #이렇게 지정하는 것이 약속임
        # 모든 필드의 정보를 읽어오게 하는 것
        fields =['author_name','message']

        # 항상 오타 확인, forms 이름 !!

mydjango17/diary/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse

# 포스팅 목록 보여주기
# 모든 함수는 타입을 명시하는 습관을 들여야함!!
from diary.models import Post


# 모든 이름은 의미 있게 지어야 한다!!!!!!!!!!!!!!!!!!!!!


def tag_detail(request: HttpRequest, tag_name: str) -> HttpResponse:  # 태그에도 pk가 있긴한데 주로 name으로 씀
    qs = Post.objects.all()
    qs = qs.filter(tag_set__name=tag_name)
    return render(request,"diary/tag_detail.html",{
        "tag_name":tag_name,
        "post_list":qs,
    })


def post_list(request: HttpRequest) -> HttpResponse:
    qs = Post.objects.all()  # 전체 포스팅 목록을 얻어올 준비
    # 얻어올 준비라는 것은? 아직 얻어오지 않는다는 것~
    # 요청이 들어올 때에만, 주문이 들어올때에만 하나를 생산하고 추가시킨다 ~

    #검색 기능 구현 시 추가
    query = request.GET.get("query", "")  # query라는 이름의 값이 있으면 값을 가져오고, 없으면 빈 문자열을 반환
    if query:  # 검색어가 있다면?
        qs = qs.filter(title__icontains=query)
    # 주문이 들어올 때까지 DB에 접근을 안한다!

    context_data = {
        "post_list": qs,  # 이름이 같다고 담고있는 데이터도 같은 것은 아니다!
    }

    return render(request, "diary/post_list.html", {
        "post_list": qs,  # qs 넘겨주기
    })


# render함수는 인자를 총 세개를 가짐
# views가 가진 request, "어떤 경로를 해서 html을 응답", 어떤 랜더링
# 두번째 인자에 꼭 앱이름/모델명_lsit.html

# 모델명_detail(첫번째 인자는 항상 request: HttpRequest) -> HttpResponse
# 두번째 인자는 pk : int (정수)
# detail에서는 두번째 인자가 필요해서, 어떤 링크의 디테일을 보여줄지 pk:int로 받음
def post_detail(request: HttpRequest, pk: int) -> HttpResponse:
    post = Post.objects.get(pk=pk)  # 전체 포스팅 목록을 얻어올 준비
    # 매칭되는 post가 한개이길 기대!
    # pk는 절대 중복될 수 없음!
    # pk에 해당되는 애들은 한개이거나 없거나 둘 중 하나임
    # pk(모델에서 지원하는 필드명, 명시적으로 PK를 조회할거야) = pk

    # 각자의 포스팅에 속한 comment을 받기
    comment_list = post.comment_set.all()
    tag_list = post.tag_set.all()

    # render(request, 모델명/모델명_detail (템플릿경로)
    # 주문이 들어올 때까지 DB에 접근을 안한다!
    return render(request, "diary/post_detail.html", {
        "post": post,  # qs 넘겨주기
        "comment_list": comment_list,
        "tag_list": tag_list,
    })

mydjango18/diary/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse

# list_list.html 생성
from diary.models import Post


def post_list(request: HttpRequest) -> HttpResponse:
    qs = Post.objects.all()  # 전체 포스팅 얻어올 준비
    context_data = {
        "post_list": qs,
    }
    # 검색 구현 기능 시 필요
    query = request.GET.get('query', '')
    if query:
        qs = qs.filter(title__icontains=query)

    # 여기서 context_data로 받는 이유는 return할때 render 함수를 쓸 건데
    # 여기서 필요한 게 사전 형식으로 받은 데이터임

    return render(request, "diary/post_list.html",
                  {
                      "post_list": qs,  # qs넘겨주기
                  })


# 여기서는 인자를 두 개 받아야 함. detail은 인자가 두개 필요해!
def post_detail(request: HttpRequest, pk: int) -> HttpResponse:
    post = Post.objects.get(pk=pk)
    templates_name = 'diary/post_list.html'
    context_data = {
        "post": post,
    }
    comment_list = post.comment_set.all()
    tag_list = post.tag_set.all()

    return render(request, 'diary/post_detail.html', {
        "post": post,
        "comment_list": comment_list,
        "tag_list": tag_list,
    })


def tag_detail(request: HttpRequest, tag_name: str) -> HttpResponse:
    qs = Post.objects.all()
    qs = qs.filter(tag_set__name=tag_name)

    return render(request, "diary/tag_detail.html", {
        "tag_name": tag_name,
        "post_list": qs,
    })

mydjango19/diary/views.py
from idlelib.autocomplete import FILES

from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpRequest, HttpResponse, Http404
from diary.forms import PostForm, CommentForm
from diary.models import Post, Comment
from django.contrib import messages


def tag_detail(request: HttpRequest, tag_name: str) -> HttpResponse:  # 태그에도 pk가 있긴한데 주로 name으로 씀
    qs = Post.objects.all()
    qs = qs.filter(tag_set__name=tag_name)
    return render(request, "diary/tag_detail.html", {
        "tag_name": tag_name,
        "post_list": qs,
    })


def post_list(request: HttpRequest) -> HttpResponse:
    qs = Post.objects.all()
    query = request.GET.get("query", "")
    if query:
        qs = qs.filter(title__icontains=query)

    context_data = {
        "post_list": qs,
    }
    return render(request, "diary/post_list.html", {
        "post_list": qs,
    })


def post_detail(request: HttpRequest, pk: int) -> HttpResponse:
    # try:  # 하단의 들여쓰기밑에 있는 코드를 실행해서, 예외가 발생하는 지 보는 것
    #     post = Post.objects.get(pk=pk)  # DoesNotExist 예외
    #
    # except Post.DoesNotExist:  # 클래스.DoesNotExist -> 없다는 오류가 발생하면?
    #     # 밑에 있는 코드를 실행해라
    #     raise Http404
    #     # 예외발생 시 raise

    post = get_object_or_404(Post,pk=pk)



    comment_list = post.comment_set.all()
    tag_list = post.tag_set.all()

    return render(request, "diary/post_detail.html", {
        "post": post,  # qs 넘겨주기
        "comment_list": comment_list,
        "tag_list": tag_list,
    })


def post_new(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)  # ModelForm에서만 지원
            post.ip = request.META['REMOTE_ADDR']
            post.save()
            messages.success(request, "성공적으로 저장했습니다.")
            return redirect("diary:post_list")

    else:
        form = PostForm()

    return render(request, "diary/post_form.html", {
        "form": form,
    })


# 수정도 detail처럼 수정대상을 지정하기 위해 pk를 인자로 받아줘야함
def post_edit(request: HttpRequest, pk: int) -> HttpResponse:
    # 아래 코드는 ModelForm에 한해서 동작하는 코드 ! (Form코드는 좀 다름)
    # 수정대상(pk)에 접근해서 읽어옴
    post = get_object_or_404(Post,pk=pk)

    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            messages.success(request, "성공적으로 수정했습니다.")
            return redirect("diary:post_list")

    else:
        form = PostForm(instance=post)

    return render(request, "diary/post_form.html", {
        "form": form,
    })


# 두번째 인자는 가변적으로 바뀌는 url
# 가변적으로 바뀌는 부분을 캡쳐
# -> 캡쳐해서, 어떤 특정 이름으로 장고가 넘겨주도록 할 수 있음

# /diary/100/comments/new/
# -> HttpResponse 리턴타입임
def comment_new(request: HttpRequest, post_pk: int) -> HttpResponse:
    post = get_object_or_404(Post,pk=post_pk)

    # 입력서식 만들기
    if request.method == "POST":
        form = CommentForm(request.POST, request.FILES)
        if form.is_valid():
            # 유효성 검사를 하고,  다 성공해야지만 is_vaild() 실행.
            comment = form.save(commit=False)  # 유효성검사에 다 통과된 데이터만 저장됨
            # 저장된 comment만
            # comment.post_id = post_pk #FK를 직접 채우지는 않음 / 할수는 있으나
            comment.post = post  # post모델 인스턴스
            comment.save()

        return redirect("diary:post_detail", post_pk)
        # 저장되면 해당 post_detail로 넘어감
    else:
        form = CommentForm()
    # 템플릿에서 사용할 값을 이름과 함께 넘겨줘야만,
    # 템플릿에서 그 이름으로 접근할 수 있는 것
    return render(request, "diary/comment_form.html", {
        "form": form,

    })
    # _form.html은 하나의 약속임


# /diary/100/comments/20/edit
def comment_edit(request: HttpRequest, post_pk: int, pk: int) -> HttpResponse:
    comment = get_object_or_404(Comment,pk=pk)
    # 지정 pk에 Comment가 없으면 404 오류가 뜨게 !
    if request.method =="POST":
        form = CommentForm(request.POST, request.FILES,instance=comment)
        if form.is_vaild():
            form.save()
            return redirect("diary:post_detail",post_pk)
    else:
        form = CommentForm(instance=comment)

    return render(request,"diary/comment_form.html",{
        "form" : form, #수정 서식만 보여줌.
    })

myhomework17/diary/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse

# 포스팅 목록 보여주기
# 모든 함수는 타입을 명시하는 습관을 들여야함!!
from diary.models import Post


# 모든 이름은 의미 있게 지어야 한다!!!!!!!!!!!!!!!!!!!!!


def tag_detail(request: HttpRequest, tag_name: str) -> HttpResponse:  # 태그에도 pk가 있긴한데 주로 name으로 씀
    qs = Post.objects.all()
    qs = qs.filter(tag_set__name=tag_name)
    return render(request, "diary/tag_detail.html", {
        "tag_name": tag_name,
        "post_list": qs,
    })


def post_list(request: HttpRequest) -> HttpResponse:
    qs = Post.objects.all()  # 전체 포스팅 목록을 얻어올 준비
    # 얻어올 준비라는 것은? 아직 얻어오지 않는다는 것~
    # 요청이 들어올 때에만, 주문이 들어올때에만 하나를 생산하고 추가시킨다 ~

    # 검색 기능 구현 시 추가
    query = request.GET.get("query", "")  # query라는 이름의 값이 있으면 값을 가져오고, 없으면 빈 문자열을 반환
    if query:  # 검색어가 있다면?
        qs = qs.filter(title__icontains=query)
    # 주문이 들어올 때까지 DB에 접근을 안한다!

    context_data = {
        "post_list": qs,  # 이름이 같다고 담고있는 데이터도 같은 것은 아니다!
    }

    return render(request, "diary/post_list.html", {
        "post_list": qs,  # qs 넘겨주기
    })


# render함수는 인자를 총 세개를 가짐
# views가 가진 request, "어떤 경로를 해서 html을 응답", 어떤 랜더링
# 두번째 인자에 꼭 앱이름/모델명_lsit.html

# 모델명_detail(첫번째 인자는 항상 request: HttpRequest) -> HttpResponse
# 두번째 인자는 pk : int (정수)
# detail에서는 두번째 인자가 필요해서, 어떤 링크의 디테일을 보여줄지 pk:int로 받음
def post_detail(request: HttpRequest, pk: int) -> HttpResponse:
    post = Post.objects.get(pk=pk)  # 전체 포스팅 목록을 얻어올 준비
    # 매칭되는 post가 한개이길 기대!
    # pk는 절대 중복될 수 없음!
    # pk에 해당되는 애들은 한개이거나 없거나 둘 중 하나임
    # pk(모델에서 지원하는 필드명, 명시적으로 PK를 조회할거야) = pk

    # 각자의 포스팅에 속한 comment을 받기
    comment_list = post.comment_set.all()
    tag_list = post.tag_set.all()

    # render(request, 모델명/모델명_detail (템플릿경로)
    # 주문이 들어올 때까지 DB에 접근을 안한다!
    return render(request, "diary/post_detail.html", {
        "post": post,  # qs 넘겨주기
        "comment_list": comment_list,
        "tag_list": tag_list,
    })

mynote2/diary/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse

from diary.models import Post


def post_list(request: HttpRequest) -> HttpResponse:
    qs = Post.objects.all()  # 전체 포스팅 목록을 얻어올 준비
    context_data = {
        "post_list": qs,
    }
    query = request.GET.get("query", "")  # query라는 이름의 값이 있으면 값을 가져오고, 없으면 빈 문자열을 반환
    if query:  # 검색어가 있다면?
        qs = qs.filter(title__icontains=query)

    return render(request, "diary/post_list.html", {
        "post_list": qs,  # qs 넘겨주기
    })



def post_detail(request: HttpRequest, pk: int) -> HttpResponse:

    post = Post.objects.get(pk=pk)		# 전체 포스팅 목록을 얻어올 준비
    templates_name = "diary/post_list.html"
    context_data = {
        "post": post,
    }

    # 각자의 포스팅에 속한 comment을 받기
    comment_list = post.comment_set.all() # 위에서 얻어온 포스팅 목록의 post
    tag_list = post.tag_set.all()

    # render(request, 모델명/모델명_detail (템플릿경로)
    # 주문이 들어올 때까지 DB에 접근을 안한다!
    return render(request, "diary/post_detail.html", {
        "post": post,  # qs 넘겨주기
        "comment_list": comment_list,
        "tag_list": tag_list,
    })

mynote3/diary/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse

# 포스팅 목록 보여주기
# 모든 함수는 타입을 명시하는 습관을 들여야함!!
from diary.models import Post


# 모든 이름은 의미 있게 지어야 한다!!!!!!!!!!!!!!!!!!!!!


def tag_detail(request: HttpRequest, tag_name: str) -> HttpResponse:  # 태그에도 pk가 있긴한데 주로 name으로 씀
    qs = Post.objects.all()
    qs = qs.filter(tag_set__name=tag_name)
    return render(request,"diary/tag_detail.html",{
        "tag_name":tag_name,
        "post_list":qs,
    })


def post_list(request: HttpRequest) -> HttpResponse:
    qs = Post.objects.all()  # 전체 포스팅 목록을 얻어올 준비
    # 얻어올 준비라는 것은? 아직 얻어오지 않는다는 것~
    # 요청이 들어올 때에만, 주문이 들어올때에만 하나를 생산하고 추가시킨다 ~

    #검색 기능 구현 시 추가
    query = request.GET.get("query", "")  # query라는 이름의 값이 있으면 값을 가져오고, 없으면 빈 문자열을 반환
    if query:  # 검색어가 있다면?
        qs = qs.filter(title__icontains=query)
    # 주문이 들어올 때까지 DB에 접근을 안한다!

    context_data = {
        "post_list": qs,  # 이름이 같다고 담고있는 데이터도 같은 것은 아니다!
    }

    return render(request, "diary/post_list.html", {
        "post_list": qs,  # qs 넘겨주기
    })


# render함수는 인자를 총 세개를 가짐
# views가 가진 request, "어떤 경로를 해서 html을 응답", 어떤 랜더링
# 두번째 인자에 꼭 앱이름/모델명_lsit.html

# 모델명_detail(첫번째 인자는 항상 request: HttpRequest) -> HttpResponse
# 두번째 인자는 pk : int (정수)
# detail에서는 두번째 인자가 필요해서, 어떤 링크의 디테일을 보여줄지 pk:int로 받음
def post_detail(request: HttpRequest, pk: int) -> HttpResponse:
    post = Post.objects.get(pk=pk)  # 전체 포스팅 목록을 얻어올 준비
    # 매칭되는 post가 한개이길 기대!
    # pk는 절대 중복될 수 없음!
    # pk에 해당되는 애들은 한개이거나 없거나 둘 중 하나임
    # pk(모델에서 지원하는 필드명, 명시적으로 PK를 조회할거야) = pk

    # 각자의 포스팅에 속한 comment을 받기
    comment_list = post.comment_set.all()
    tag_list = post.tag_set.all()

    # render(request, 모델명/모델명_detail (템플릿경로)
    # 주문이 들어올 때까지 DB에 접근을 안한다!
    return render(request, "diary/post_detail.html", {
        "post": post,  # qs 넘겨주기
        "comment_list": comment_list,
        "tag_list": tag_list,
    })

mydjango19/diary/templates/diary/comment_form.html
{% extends "diary/layout.html" %}
{% load bootstrap5 %}


{% block content %}

    <h2>Comment Form</h2>
    <form action="" method="post" enctype="multipart/form-data"> 입력폼은 항상 빈 서식
        {%  csrf_token %}
        {% bootstrap_form form %}
        <input type="submit"
               value="저장하기"
               class="btn alert-danger"/>
    </form>

{% endblock %}

mydjango19/diary/templates/diary/layout.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>유나의 다이어리</title>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <script src="//cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"></script>

    <style>
        body {
            padding-bottom: 1em;
        }
    </style>

</head>
<body>
<div class="container.py-3">
    <header class="p-3 bg-white text-dark">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="{% url "root" %}" class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">
                <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap">
                    <use xlink:href="#bootstrap"></use>
                </svg>
                <span class="fs-2">김유나의 블로그</span>
            </a>


            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="#" class="nav-link px-2 text-secondary">초롱이</a></li>
                <li><a href="#" class="nav-link px-2 text-secondary">꼬마</a></li>

            </ul>

            <form action="" method="get" class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
                <div style="display: flex; height: 40px;">
                    <input type="search"
                           class="form-control form-control-dark"
                           style="margin-right: 0.3em;"
                           placeholder="Search..."
                           aria-label="Search"
                           name="query" value="{{ request.GET.query }}">
                    <button class="btn btn-sm alert-danger" style="width: 80px;">검색</button>
                </div>
            </form>

            <div class="text-end">
            </div>
        </div>
</div>
</header>

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>

    {% endfor %}

{% endif %}


{% block content %} {% endblock %}

</div>

</hr>

&copy; 2021. 김초롱 컴퍼니 ♥


</div>

</body>
</html>

mydjango19/diary/templates/diary/post_detail.html
{% extends "diary/layout.html" %}


{% block content %}


    <table class="table table-hover table-bordered">
        <thead>
            <tr>
                <th><h2>{{ post.title }}</h2></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    {{ post.content|linebreaks }}
                    <img src ="{{ post.photo.url }}" alt="{{ post.title }}" width="100%"/>
                </td>
            </tr>

        </tbody>
    </table>

    <p>
        태그:
        {% for tag in tag_list %}
            <a href="{% url "diary:tag_detail" tag.name %}" class= "badge alert-danger ">
                {{ tag.name }}

            </a>
        {% endfor %}

    </p>

    <h3>댓글</h3>

    <a href="{% url "diary:comment_new" post.pk %}">댓글 쓰기 </a>
    <ul>
        {% for comment in comment_list %}
            <li>
                {{ comment.message }}
                by {{ comment_author_name }}
                at
               <span title="{{ comment.created_at }}">
                   {{ comment.created_at|timesince }} 전
               </span>


                <a href="{% url "diary:comment_edit" post.pk comment.pk %}">Edit</a>

            </li>
        {% endfor %}

    </ul>



    <a href="{% url "diary:post_list" %}">목록으로</a>
    <a href="{% url "diary:post_edit" post.pk %}">수정</a>



{% endblock %}

mydjango19/diary/templates/diary/post_form.html
{% extends 'diary/layout.html' %}
{% load bootstrap5 %}


{% block content %}
    <h2>Post Form</h2>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="저장하기" />

    </form>

    <hr/>
{% endblock %}

mydjango19/diary/templates/diary/post_list.html
{% extends "diary/layout.html" %}
{% block content %}
    <a href="{% url "diary:post_new" %}" class="btn alert-danger">
        포스팅 쓰기
    </a>

    <form action="" method="get" >
        <input type="text"
               name="query"
               value="{{ request.GET.query }}"
               placeholder="검색어를 입력해주세요." />
        <input type="submit" value="검색" />
    </form>
    <div class="row" style="margin-top: 1em;">
        {% for post in post_list %}
            <div class="col-sm-6 offset-sm-3" style="margin-bottom: 1em;">
                <div class="card">
                    <img src="{{ post.photo.url }}"
                         alt="{{ post.title }}"
                         class="card-img-top" />
                    <div class="card-body">
                        <h5 class="card-title">{{ post.title }}{{ post.pk }}</h5>
                        {{ post.content|truncatewords:20 }}
                        <a href="{% url "diary:post_detail" post.pk %}" class="btn btn-sm alert-danger">
                            바로 가기
                        </a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <hr/>

{% endblock %}

mydjango19/diary/templates/diary/tag_detail.html
{% extends "diary/layout.html" %}

{% block content %}
    <h2>{{ tag_name }}</h2>
    <div>
        {% for post in post_list %}
            <div>
                <a href="{% url "diary:post_detail" post.pk%}">
                    {{ post.title }}
                </a>
            </div>
        {% endfor %}


    </div>

{% endblock %}